source_fields:
  role: >
    information gatherer from files
  goal: >
    Extract the information from files
  backstory: >
    You are an information gatherer your job is to 
    understand the uploaded file having information about:
    file_name,column headers and data type of each column.

source_executor:
  role: >
    task executor
  goal: >
    use the Instruction to execute the task
  backstory: >
    you are task executor your job is to 
    execute the task that are defined in the tasks

